#!/usr/bin/env bash
set -e

sed -i -e 's/#DAEMON_CONF=""/DAEMON_CONF="\/etc\/hostapd.conf"/g' /etc/default/hostapd
sed -i -e 's/DHCPD_ENABLED="no"/#DHCPD_ENABLED="no"/g' /etc/default/udhcpd
sed -i -e 's/worker_processes auto;/worker_processes 1;/g' /etc/nginx/nginx.conf

systemctl enable hostapd
systemctl enable udhcpd
systemctl enable nginx
systemctl enable /etc/systemd/system/pitot.service

cd /tmp/pitot/librtlsdr && mkdir build \
&& cd build \
&& cmake ../ -DINSTALL_UDEV_RULES=ON \
&& make \
&& make install

cd /tmp/pitot/dump1090 \
&& make \
&& make install

cd /tmp/pitot/dump978 \
&& make \
&& make install

cp -r /tmp/pitot/pitot/webui/* /var/www/html

rm -rf /tmp/pitot

ldconfig

# disable HDMI
sed -i -e '$i \/usr/bin/tvservice -o\n' /etc/rc.local

echo 'net.core.rmem_max = 10485760' >> /etc/sysctl.conf
echo 'net.core.rmem_default = 10485760' >> /etc/sysctl.conf
echo 'net.core.wmem_max = 10485760' >> /etc/sysctl.conf
echo 'net.core.wmem_default = 10485760' >> /etc/sysctl.conf
echo 'vm.min_free_kbytes = 16384' >> /etc/sysctl.conf

# SKIP_BACKUP=1 rpi-update

setcap CAP_SYS_TIME,CAP_NET_RAW+ep /usr/local/bin/pitot

groupadd i2c
usermod -a -G i2c pi
echo "i2c-dev" >> /etc/modules
